name: srm_kitchen
description: "SRM Kitchen - Premium Food Ordering App for SRM"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Fonts
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8

  # Utilities
  intl: ^0.18.0
  qr_flutter: ^4.1.0

  # State Management
  provider: ^6.0.5

  # Database (Hive)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
