dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0  # Saves data
  google_fonts: ^6.1.0        # Professional Fonts
  qr_flutter: ^4.1.0          # QR Code
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
