name: saints_kitchen
description: A premium food ordering app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Local Storage (Remembers login)
  shared_preferences: ^2.2.0
  # Beautiful Fonts
  google_fonts: ^6.1.0
  # Icons & QR
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# THIS PART IS CRITICAL FOR ICONS
flutter:
  uses-material-design: true
